# -*- coding: utf-8 -*-
"""GenAILab2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VYznHrZbVxjX384CsnEu4ZjcNTyuoYut

Part-1

Simple practical application using Langchain which provides 3 sentences on the entered topic.LangChain is a framework that helps developers build applications using large language models by connecting prompts, models, memory, and external tools into structured workflows.
"""

pip install langchain langchain-community transformers accelerate sentencepiece

import os
os.environ["GROQ_API_KEY"] = "Enter Your API"

pip install langchain_groq

from langchain_groq import ChatGroq
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser

llm = ChatGroq(
    model="llama-3.1-8b-instant",
    temperature=0.3
)

prompt = PromptTemplate.from_template(
    "Explain {topic} in exactly 3 bullet points for a beginner."
)

chain = prompt | llm | StrOutputParser()
topic=input("Enter a topic name:")
print(chain.invoke({"topic": topic}))

"""Performing simple data analysis on a kaggle dataset(Netflix vs TV Shows).It was analyzed by checking rows, columns, and missing values.
Basic exploratory analysis was performed to study content distribution such as Movies vs TV Shows, top countries, and release years.
Simple visualizations were created to understand trends and patterns in the dataset.
"""

pip install kaggle

import kagglehub

# Download latest version
path = kagglehub.dataset_download("shivamb/netflix-shows")

print("Path to dataset files:", path)

import pandas as pd

df = pd.read_csv(path + "/netflix_titles.csv")
df.head()

"""Simple data analysis of the dataset"""

df.shape

df.columns

df.isnull().sum()

df["type"].value_counts()

df["country"].value_counts().head()

df["release_year"].value_counts().sort_index().tail(10)

import matplotlib.pyplot as plt

df["type"].value_counts().plot(kind="bar")
plt.title("Netflix Movies vs TV Shows")
plt.show()

"""Part-2

A simple image classification task was performed using FastAI.
The MNIST sample dataset was loaded, a pretrained ResNet model was fine-tuned for one epoch, and predictions were generated on sample images.
"""

pip install fastai

!pip -q install fastai fastprogress==1.0.3

from fastprogress.fastprogress import force_console_behavior
force_console_behavior()

!pip -q install fastai

from fastai.vision.all import *
from fastprogress.fastprogress import force_console_behavior

force_console_behavior()  # <-- fixes NBMasterBar 'out' error in Colab

path = untar_data(URLs.MNIST_SAMPLE)

dls = ImageDataLoaders.from_folder(
    path, train="train", valid="valid",
    item_tfms=Resize(28), bs=64
)

learn = vision_learner(dls, resnet18, metrics=accuracy)

learn.fit_one_cycle(1)

img = PILImage.create(get_image_files(path/"valid"/"3")[0])
print("Prediction:", learn.predict(img)[0])

"""Using Hugging Face Transformers, basic NLP tasks were implemented such as sentiment analysis, translation, and text summarization.
Sentence embeddings were generated using a pretrained SentenceTransformer model to measure semantic similarity between sentences.
"""

!pip -q install transformers sentence-transformers torch sentencepiece accelerate

from transformers import pipeline

sentiment = pipeline("sentiment-analysis")
print(sentiment("This project is amazing and super easy."))
print(sentiment("This is frustrating and confusing."))

from transformers import pipeline

translator = pipeline("translation_en_to_fr", model="Helsinki-NLP/opus-mt-en-fr")
print(translator("I am doing my NLP practical in Google Colab.")[0]["translation_text"])

from transformers import pipeline

summarizer = pipeline("text2text-generation", model="google/flan-t5-base")
text="""Hugging Face is an open-source AI platform that provides tools, libraries, and pretrained models for building machine learning applications.
It is best known for the Transformers library, which makes it easy to use state-of-the-art models for tasks like sentiment analysis, translation, summarization, and text generation.
The Hugging Face Hub hosts thousands of public models and datasets that researchers and developers can reuse without training from scratch.
It also supports fine-tuning models for custom tasks and deploying them for real applications.
Because of this, Hugging Face is widely used in both industry and academia for NLP and other AI workflows."""
print(
    summarizer(
        "Summarize the following text by capturing only the main ideas:\n" + text,
        max_new_tokens=60,
        do_sample=False
    )[0]["generated_text"]
)